const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json","cache-control":"no-store"}});
function config(){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY,pin=process.env.ADMIN_PIN;if(!url||!key||!pin)throw new Error("Server setup incomplete");return{url,key,pin}}
async function query(path,options={}){const{url,key}=config(),r=await fetch(`${url}/rest/v1/${path}`,{...options,headers:{apikey:key,authorization:`Bearer ${key}`,"content-type":"application/json",...(options.headers||{})}});const text=await r.text(),data=text?JSON.parse(text):null;if(!r.ok)throw new Error(data?.message||"Database error");return data}
export default async(req)=>{try{const u=new URL(req.url),action=u.searchParams.get("action"),body=req.method==="POST"?await req.json():{};
 if(action==="status"){const token=u.searchParams.get("token")||"",rows=await query(`spin_links?token=eq.${encodeURIComponent(token)}&select=customer_name,status,prize,used_at&limit=1`);if(!rows.length)return json({error:"यह Spin link सही नहीं है।"},404);const r=rows[0];return json({name:r.customer_name,status:r.status,prize:r.status==="used"?r.prize:null,usedAt:r.used_at})}
 if(action==="claim"){const token=body.token||"",now=new Date().toISOString(),rows=await query(`spin_links?token=eq.${encodeURIComponent(token)}&status=eq.pending`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({status:"used",used_at:now})});if(!rows.length)return json({error:"यह Lucky Spin पहले ही इस्तेमाल हो चुका है।"},409);return json({prize:rows[0].prize,usedAt:now})}
 const{pin}=config();if(body.pin!==pin)return json({error:"गलत Admin PIN"},401);if(action==="login")return json({ok:true});
 if(action==="list"){const rows=await query("spin_links?select=id,token,customer_name,mobile,prize,status,created_at,used_at&order=id.desc&limit=50");return json({links:rows})}
 if(action==="create"){if(!body.name?.trim()||!/^[0-9]{10}$/.test(body.mobile||"")||!body.prize)return json({error:"सही नाम, 10-digit mobile और Gift चुनें"},400);const token=crypto.randomUUID().replaceAll("-","")+crypto.randomUUID().slice(0,8);await query("spin_links",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({token,customer_name:body.name.trim(),mobile:body.mobile,prize:body.prize,status:"pending"})});return json({token})}
 return json({error:"Invalid action"},400)
}catch(e){return json({error:e instanceof Error?e.message:"Server error"},500)}};
