[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/spin"
  to = "/spin.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
